version: "3.9"
services:

  todotests:
    build: ./todo-app/tests/
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront

  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:3001
    restart: on-failure

networks:
  FRONT_HOST:
  BACK_HOST: